apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ikpzzcjb0-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:66334a00466f98395a7d54df18e43a8c5381e1fb@sha256:721a3b591a6c8e5d33ee686f19958abe688a15176420a1aa5c68a28c27beaac7
          name: container-image
